// @ts-nocheck
import { Coffee, Heart, Leaf, Sun, Users } from 'lucide-react';
import { Editable } from '@/components/editor/ui/Editable';

export function About({ props = {}, theme, onChange }: any) {
    const bg = theme?.bg || '#382116';
    const bgSecond = theme?.['bg-second'] || '#f1eadf';
    const ink = theme?.ink || '#f1eadf';
    const inkSecond = theme?.['ink-second'] || '#382116';
    const surface = theme?.surface || 'rgba(241, 234, 223, 0.14)';
    const accent = theme?.accent || '#c98a50';
  const fontBody = theme?.fontBody || "Inter";
    const points = [{ icon: Leaf, title: 'Good ingredients', text: 'Seasonal, local, and always worth talking about.' }, { icon: Heart, title: 'Good energy', text: 'A warm room for regulars, visitors, and first dates.' }, { icon: Sun, title: 'Good timing', text: 'Morning light, afternoon cake, and no reason to hurry.' }];
    return <section id="about" className="px-5 py-24 sm:px-8" style={{ backgroundColor: bg, color: ink , fontFamily: fontBody }}><div className="mx-auto max-w-6xl"><div className="mb-14 flex items-center justify-center gap-4 text-[9px] uppercase tracking-[0.22em]" style={{ color: `${ink}77` }}><span className="h-px w-12" style={{ backgroundColor: surface }} /><Coffee size={14} style={{ color: accent }} /><Editable value={props?.divider || 'Take the long way'} /><span className="h-px w-12" style={{ backgroundColor: surface }} /></div><div className="grid gap-14 lg:grid-cols-[1fr_1.15fr] lg:items-end"><div><p className="text-[9px] uppercase tracking-[0.2em]" style={{ color: accent }}><Editable value={props?.label || 'Our point of view'} /></p><h2 className="mt-5 max-w-md font-fraunces text-6xl leading-[0.9] tracking-[-0.05em] sm:text-8xl"><Editable value={props?.headline || 'Little details. Big feeling.'} onChange={(v) => onChange?.({ headline: v })} /></h2></div><div><p className="max-w-lg text-base leading-7" style={{ color: `${ink}99` }}><Editable value={props?.story || 'Morrow is a tiny coffee studio with a generous point of view. We care about the crop, the crumb, the playlist, and the pause between one thing and the next.'} onChange={(v) => onChange?.({ story: v })} /></p><div className="mt-8 flex items-center gap-3 text-xs" style={{ color: `${ink}bb` }}><span className="grid h-9 w-9 place-items-center rounded-full" style={{ backgroundColor: accent, color: bg }}><Users size={15} /></span><Editable value={props?.teamLine || 'Made by a small team with big care.'} /></div></div></div><div className="mt-16 grid gap-px sm:grid-cols-3" style={{ backgroundColor: surface }}>{points.map(({ icon: Icon, title, text }) => <div key={title} className="p-7" style={{ backgroundColor: bg }}><Icon size={20} style={{ color: accent }} /><h3 className="mt-16 font-fraunces text-3xl"><Editable value={title} /></h3><p className="mt-3 text-sm leading-6" style={{ color: `${ink}88` }}><Editable value={text} /></p></div>)}</div><div className="mt-14 grid grid-cols-2 gap-5 border-t pt-7 sm:grid-cols-4" style={{ borderColor: surface }}><div><p className="font-fraunces text-4xl" style={{ color: accent }}>07</p><p className="mt-2 text-[9px] uppercase tracking-[0.17em]" style={{ color: `${ink}77` }}><Editable value="days open" /></p></div><div><p className="font-fraunces text-4xl" style={{ color: accent }}>03</p><p className="mt-2 text-[9px] uppercase tracking-[0.17em]" style={{ color: `${ink}77` }}><Editable value="daily rituals" /></p></div><div><p className="font-fraunces text-4xl" style={{ color: accent }}>18</p><p className="mt-2 text-[9px] uppercase tracking-[0.17em]" style={{ color: `${ink}77` }}><Editable value="house beans" /></p></div><div><p className="font-fraunces text-4xl" style={{ color: accent }}>∞</p><p className="mt-2 text-[9px] uppercase tracking-[0.17em]" style={{ color: `${ink}77` }}><Editable value="reasons to return" /></p></div></div></div></section>;
}
