export type Template = {
  slug: string;
  name: string;
  tagline: string;
  category: "Developer" | "Designer" | "Photographer" | "Writer" | "Startup" | "Minimal";
  palette: [string, string, string];
  accent: string;
  layout: "split" | "stack" | "grid" | "editorial" | "gallery" | "mono";
  isPro?: boolean;
};

export const TEMPLATES: Template[] = [
  {
    slug: "atlas",
    name: "Atlas",
    tagline: "Editorial serif portfolio for writers & founders.",
    category: "Writer",
    palette: ["#f7f4ec", "#1a1a1a", "#c9662a"],
    accent: "#c9662a",
    layout: "editorial",
  },
  {
    slug: "orbit",
    name: "Orbit",
    tagline: "Bold, kinetic layout for product designers.",
    category: "Designer",
    palette: ["#ffffff", "#0a0a0a", "#ff5b3a"],
    accent: "#ff5b3a",
    layout: "split",
  },
  {
    slug: "monoline",
    name: "Monoline",
    tagline: "Pure typography, engineered for developers.",
    category: "Developer",
    palette: ["#fafafa", "#111111", "#3f6fdf"],
    accent: "#3f6fdf",
    layout: "mono",
  },
  {
    slug: "gallery",
    name: "Gallery",
    tagline: "Full-bleed grid for photographers.",
    category: "Photographer",
    palette: ["#ffffff", "#1c1c1c", "#a08966"],
    accent: "#a08966",
    layout: "gallery",
    isPro: true,
  },
  {
    slug: "north",
    name: "North",
    tagline: "Minimal one-page CV with quiet confidence.",
    category: "Minimal",
    palette: ["#fbfaf7", "#111111", "#6b7280"],
    accent: "#6b7280",
    layout: "stack",
  },
  {
    slug: "prism",
    name: "Prism",
    tagline: "Playful, colorful landing for creative studios.",
    category: "Startup",
    palette: ["#fff8f0", "#111111", "#e94a75"],
    accent: "#e94a75",
    layout: "grid",
    isPro: true,
  },
  {
    slug: "harbor",
    name: "Harbor",
    tagline: "Case-study-first layout for UX designers.",
    category: "Designer",
    palette: ["#f4f2ee", "#0e0e0e", "#2d6a4f"],
    accent: "#2d6a4f",
    layout: "editorial",
  },
  {
    slug: "signal",
    name: "Signal",
    tagline: "Terminal-inspired portfolio for engineers.",
    category: "Developer",
    palette: ["#0b0b0b", "#f5f5f5", "#7cffb2"],
    accent: "#7cffb2",
    layout: "mono",
    isPro: true,
  },
  {
    slug: "meridian",
    name: "Meridian",
    tagline: "Warm, human portfolio for freelancers.",
    category: "Minimal",
    palette: ["#fdf7ee", "#20140a", "#d97742"],
    accent: "#d97742",
    layout: "stack",
  },
  {
    slug: "nova",
    name: "Nova",
    tagline: "Vibrant gradient portfolio for creative directors.",
    category: "Designer",
    palette: ["#0f0f1a", "#f0f0f0", "#a855f7"],
    accent: "#a855f7",
    layout: "split",
    isPro: true,
  },
  {
    slug: "slate",
    name: "Slate",
    tagline: "Clean, structured portfolio for backend engineers.",
    category: "Developer",
    palette: ["#1e293b", "#e2e8f0", "#38bdf8"],
    accent: "#38bdf8",
    layout: "mono",
  },
  {
    slug: "ember",
    name: "Ember",
    tagline: "Warm, bold portfolio for brand designers.",
    category: "Designer",
    palette: ["#fef2f2", "#1c1917", "#ef4444"],
    accent: "#ef4444",
    layout: "grid",
  },
  {
    slug: "aurora",
    name: "Aurora",
    tagline: "Ethereal, dreamy layout for illustrators.",
    category: "Photographer",
    palette: ["#f0fdf4", "#14532d", "#22c55e"],
    accent: "#22c55e",
    layout: "gallery",
  },
  {
    slug: "chronicle",
    name: "Chronicle",
    tagline: "Long-form storytelling for journalists & bloggers.",
    category: "Writer",
    palette: ["#fffbeb", "#1c1917", "#d97706"],
    accent: "#d97706",
    layout: "editorial",
  },
  {
    slug: "vertex",
    name: "Vertex",
    tagline: "Angular, sharp portfolio for motion designers.",
    category: "Designer",
    palette: ["#18181b", "#fafafa", "#f59e0b"],
    accent: "#f59e0b",
    layout: "split",
    isPro: true,
  },
  {
    slug: "breeze",
    name: "Breeze",
    tagline: "Airy, spacious layout for lifestyle photographers.",
    category: "Photographer",
    palette: ["#f8fafc", "#0f172a", "#06b6d4"],
    accent: "#06b6d4",
    layout: "gallery",
  },
  {
    slug: "launch",
    name: "Launch",
    tagline: "Conversion-focused landing for SaaS founders.",
    category: "Startup",
    palette: ["#ffffff", "#0a0a0a", "#8b5cf6"],
    accent: "#8b5cf6",
    layout: "grid",
  },
  {
    slug: "ink",
    name: "Ink",
    tagline: "Minimal dark portfolio for typographers.",
    category: "Minimal",
    palette: ["#0a0a0a", "#e5e5e5", "#a3a3a3"],
    accent: "#a3a3a3",
    layout: "stack",
  },
  {
    slug: "canvas",
    name: "Canvas",
    tagline: "Art-focused portfolio for painters & mixed media.",
    category: "Photographer",
    palette: ["#fafaf9", "#1c1917", "#b45309"],
    accent: "#b45309",
    layout: "gallery",
    isPro: true,
  },
  {
    slug: "flux",
    name: "Flux",
    tagline: "Dynamic, animated portfolio for interaction designers.",
    category: "Designer",
    palette: ["#fdf4ff", "#1e1b4b", "#c026d3"],
    accent: "#c026d3",
    layout: "split",
  },
  {
    slug: "byte",
    name: "Byte",
    tagline: "Compact, data-dense portfolio for full-stack devs.",
    category: "Developer",
    palette: ["#f5f5f4", "#1c1917", "#16a34a"],
    accent: "#16a34a",
    layout: "mono",
  },
  {
    slug: "folio",
    name: "Folio",
    tagline: "Classic, timeless portfolio for copywriters.",
    category: "Writer",
    palette: ["#faf5ff", "#1e1b4b", "#7c3aed"],
    accent: "#7c3aed",
    layout: "editorial",
    isPro: true,
  },
  {
    slug: "spark",
    name: "Spark",
    tagline: "Energetic landing for marketing agencies.",
    category: "Startup",
    palette: ["#fff7ed", "#1c1917", "#ea580c"],
    accent: "#ea580c",
    layout: "grid",
  },
  {
    slug: "zen",
    name: "Zen",
    tagline: "Ultra-minimal portfolio with breathing room.",
    category: "Minimal",
    palette: ["#f5f5f0", "#262626", "#78716c"],
    accent: "#78716c",
    layout: "stack",
  },
];
