// @ts-nocheck
import { Editable } from "@/components/editor/ui/Editable";
export function Testimonials({ props = {}, theme, onChange }: any) {
  const bg = theme?.bg || "#ffffff"; const bgSecond = theme?.["bg-second"] || bg; const ink = theme?.ink || "#24201f"; const inkSecond = theme?.["ink-second"] || ink; const surface = theme?.surface || "#ded0c9"; const accent = theme?.accent || "#9e5144";
  const fontHeading = theme?.fontHeading || "Fraunces";
  const fontBody = theme?.fontBody || "Inter";
  const people = [["Mara Vale", "Creative director"], ["Jules Hart", "Designer & maker"], ["Noa Reed", "Writer & strategist"]];
  return <section id="team" className="scroll-mt-20 py-24 md:py-32" style={{ backgroundColor: bg, color: ink , fontFamily: fontBody }}><div className="mx-auto max-w-7xl px-6 md:px-12"><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><div><Editable as="p" className="text-xs font-bold uppercase tracking-widest" value="03 — The team"/><Editable as="h2" className="mt-5 text-5xl md:text-6xl" style={{ fontFamily: fontHeading }} value={props.teamTitle || "Small by design."} onChange={(teamTitle: string) => onChange?.({ teamTitle })}/></div><div><Editable as="blockquote" className="text-3xl leading-snug md:text-5xl" style={{ fontFamily: fontHeading }} value="“They found the heart of our story and gave it a visual language that finally felt like us.”"/><Editable as="p" className="mt-5 text-sm uppercase tracking-widest opacity-55" value="— A longtime collaborator"/></div></div><div className="mt-16 border-t" style={{ borderColor: surface }}>{people.map(([name,role],i) => <div key={name} className="grid gap-2 border-b py-6 sm:grid-cols-[4rem_1fr_1fr]" style={{ borderColor: surface }}><span className="text-sm opacity-45">0{i+1}</span><Editable as="h3" className="text-2xl" style={{ fontFamily: fontHeading }} value={name}/><Editable as="p" className="text-sm opacity-60" value={role}/></div>)}</div></div></section>;
}
